packages:
  - docs
  - packages/transport/blocks
  - packages/transport/blocks-interface
  - packages/transport/stream
  - packages/transport/stream-interface
  - packages/transport/stream/e2e/browser
  - packages/transport/stream/e2e/browser/browser-node
  - packages/transport/pubsub
  - packages/transport/pubsub-interface
  - packages/transport/libp2p-test-utils
  - packages/log
  - packages/clients/peerbit
  - packages/clients/peerbit-proxy/proxy
  - packages/clients/peerbit-proxy/window
  - packages/clients/peerbit-proxy/window/e2e/browser
  - packages/clients/peerbit-proxy/window/e2e/browser/parent
  - packages/clients/peerbit-proxy/window/e2e/browser/child
  - packages/clients/peerbit-server/frontend
  - packages/clients/peerbit-server/node
  - packages/clients/peerbit-server/test-lib
  - packages/clients/test-utils
  - packages/clients/vite
  - packages/clients/vite/e2e
  - packages/programs/rpc
  - packages/programs/acl/identity-access-controller
  - packages/programs/acl/trusted-network
  - packages/programs/program
  - packages/programs/clock-service
  - packages/programs/transport
  - packages/programs/data/document/*
  - packages/programs/data/*
  - packages/utils/crypto
  - packages/utils/any-store/*
  - packages/utils/build-assets
  - packages/utils/time
  - packages/utils/cache
  - packages/utils/logger
  - packages/utils/keychain
  - packages/utils/indexer/*
  - packages/utils/rateless-iblt
